---
lon-router1:
    data:
        site: london
        interfaces:
            loopback0: 1.1.1.1
        neighbor_asn: 555
        bgp_neighbor: 192.168.122.11
    hostname: 192.168.122.10
    username: randy
    password: test
    groups:
       - routers

us-router2:
    data:
        site: brussels
        interfaces:
            loopback0: 2.2.2.2
        neighbor_asn: 666
        bgp_neighbor: 192.168.122.10
    hostname: 192.168.122.11
    username: randy
    password: test
    groups:
      - routers

