---
lon-router1:
    data:
        site: london
        interfaces:
            loopback0: 1.1.1.1
    hostname: 192.168.122.10
    username: randy
    password: test
    groups:
       - routers

us-router2:
    data:
        site: brussels
    hostname: 192.168.122.11
    username: randy
    password: test
    groups:
      - routers

