---
router1:
    data:
        site: london
    hostname: 192.168.122.10
    username: randy
    password: test
    groups:
       - 'london'
    #loopback0: 1.1.1.1

router2:
    data:
        site: brussels
    hostname: 192.168.122.11
    username: randy
    password: test
    groups:
      - 'us'

