---
lon-router1:
    data:
        site: london
        interfaces:
            loopback0: 1.1.1.1
            Gig1: 6.6.6.6 255.255.255.255
            Gig2: 7.7.7.7 255.255.255.255
        neighbor_asn: 555
        bgp_neighbor: 192.168.122.11
    hostname: 192.168.122.10
    username: randy
    password: test
    groups:
       - routers

brus-router2:
    data:
        site: brussels
        interfaces:
            loopback0: 2.2.2.2
            Gig1: 8.8.8.8 255.255.255.255
            Gig2: 9.9.9.9 255.255.255.255
        neighbor_asn: 666
        bgp_neighbor: 192.168.122.10
    hostname: 192.168.122.11
    username: randy
    password: test
    groups:
      - routers

